<template>
  <NavBar> </NavBar>
  <div class="main">
    <div class="wrapper">
      <h1>Projects</h1>
      <div class="project_grid">
        <div class="project_card" v-for="(project, id) in projects" :key="id">
          <a :href="project.source_code" class="anchor"
            ><img class="projectimages" v-bind:src="project.image" alt="" />
          </a>
          <div class="projecticons">
            <div v-for="(i, id) in project.icons" :key="id">
              <i :class="i.icon"></i>
            </div>
          </div>
          <a :href="project.url" class="projecttitle">{{ project.title }}</a>
          <p class="build-with">
            {{ project.build_info }}
          </p>
          <p class="description">{{ project.description }}</p>
        </div>
      </div>
    </div>
  </div>
  <FooterBar> </FooterBar>
</template>

<script>
import NavBar from "@/components/NavBar.vue";
import FooterBar from "@/components/FooterBar.vue";
import linkshareimg from "@/assets/urlshare.png";
import cryptorankimg from "@/assets/cryptorank.png";
import notebookimg from "@/assets/project3.jpg";
import portfolioimg from "@/assets/portfolio.jpeg";
import tempmessageimg from "@/assets/tempmessage.png";
export default {
  name: "ProjectsView",
  components: {
    NavBar,
    FooterBar,
  },
  data() {
    return {
      projects: [
        {
          icons: [
            {
              icon: "fab fa-js",
            },
            {
              icon: "fab fa-vuejs",
            },
            {
              icon: "fab fa-node-js",
            },
            {
              icon: "fab fa-css3-alt",
            },
          ],
          id: "URLshare",
          image: linkshareimg,
          source_code: "https://github.com/iamsuryasonar/URLshare.git",
          build_info:
            "Built with NodeJs, Firebase Database, VueJs, Vue Router, Vuex and CSS",
          title: "URLshare",
          url: "https://urlshare.netlify.app",
          description:
            "URLshare is a URL sharing platform, which enables users to share all of their URL's with a single URL. For example 'www.urlshare.com/username'.",
        },
        {
          id: "cryptorank",
          icons: [
            {
              icon: "fab fa-java",
            },
            {
              icon: "fab fa-android",
            },
          ],
          image: cryptorankimg,
          source_code: "https://github.com/iamsuryasonar/CryptoRank.git",
          build_info: "Built with Java, XML, Volley library and Coincap Api.",
          title: "CryptoRank",
          description:
            "CryptoRank is a cryptocurrency ranking app, using the CoinCap REST API, I enabled all cryptocurrencies to be displayed rankwise with its current value in US dolars and change percentage of  it in 24 hours. I used the VOLLEY library to fetch data from CoinCap API.",
        },
        {
          id: "notebook",
          icons: [
            {
              icon: "fab fa-java",
            },
            {
              icon: "fab fa-android",
            },
          ],
          image: notebookimg,
          source_code: "https://www.github.com/iamsuryasonar/NoteBook.git",
          build_info: "Built with Java, XML and Firebase Database.",
          title: "NoteBook",
          description:
            "An android app to take important notes, I used firebase database for authentication, authorisation and storage of user data.",
        },
        {
          icons: [
            {
              icon: "fab fa-js",
            },
            {
              icon: "fab fa-vuejs",
            },
            {
              icon: "fab fa-css3-alt",
            },
            {
              icon: "fab fa-node-js",
            },
          ],
          id: "portfolio",
          image: portfolioimg,
          source_code: "https://github.com/iamsuryasonar/personalportfolio.git",
          build_info: "Built with NodeJs, HTML, CSS, VueJs.",
          title: "Portfolio",
          url: "https://iamsuryasonar.netlify.app",
          description:
            "It is a responsive portfolio website to showcase my beliefs, skills, qualifications and experiences.",
        },
        {
          icons: [
            {
              icon: "fab fa-js",
            },
            {
              icon: "fab fa-css3-alt",
            },
            {
              icon: "fab fa-node-js",
            },
          ],
          id: "tempmessage",
          image: tempmessageimg,
          source_code: "https://github.com/iamsuryasonar/tempmessage.git",
          build_info: "Built with NodeJs, ExpressJs, EJS, CSS and MongoDB",
          title: "Temp Message",
          url: "https://tempmessage.herokuapp.com",
          description:
            "Temp message is a self destructing link(url) generated by authenticated user contains an image and a caption, when visited expires in 4 minutes or 30 minutes otherwise.",
        },
      ],
      linkedin: "https://www.linkedin.com/in/iamsuryasonar",
      instagram: "https://www.instagram.com/iamsuryasonar",
      github: "https://www.github.com/iamsuryasonar",
    };
  },
};
</script>
<style scoped>
* {
  color: white;
}
body {
  overflow-x: hidden;
}
.main {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: #495c83;
  min-width: 100vw;
  min-height: 100vh;
}
.wrapper {
  margin-top: 8rem;
  margin-bottom: 2rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-width: 100vw;
  min-height: 100vh;
}
.project_grid {
  margin: 2rem auto;
  width: 60%;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr));
}
.project_card {
  display: grid;
  place-items: center;
  padding: 1.2rem 0.4rem;
  width: 100%;
}
.anchor {
  display: grid;
  place-items: center;
}
.projectimages {
  padding: 1rem;
  width: 75%;
  aspect-ratio: 1/1;
  object-fit: cover;
  border-radius: 50%;
  box-shadow: 5px 15px 30px -20px rgb(3, 1, 0);
}
.projecticons {
  font-size: 1.4rem;
  margin-top: 1rem;
  display: flex;
  flex-direction: row;
}
.projecticons i {
  margin: 0.6rem 0.6rem;
}

.project_card p {
  padding: 4px 0px;
  font-size: 14px;
}
.projecttitle {
  text-decoration-line: none;
}
.projecttitle:hover {
  color: #ffd68d;
}
@media screen and (max-width: 1400px) {
  .project_grid {
    width: 80%;
  }
  .project_card a {
    font-size: 20px;
  }
  .project_card p {
    font-size: 16px;
  }
}
@media screen and (max-width: 700px) {
  .project_grid {
    width: 90%;
  }
  .project_card a {
    font-size: 20px;
  }
  .project_card p {
    font-size: 16px;
  }
}
</style>
